# Generated by Django 5.2.4 on 2026-05-29 02:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["phrase"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="monitoring__is_acti_d0c77b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="monitoring__created_7bc4b7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitoredAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("facebook", "Facebook"), ("instagram", "Instagram")],
                        max_length=20,
                    ),
                ),
                ("account_url", models.URLField(max_length=1000, unique=True)),
                ("account_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "check_interval_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(5)],
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=50)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["platform", "account_name"],
                "indexes": [
                    models.Index(
                        fields=["platform", "is_active"],
                        name="monitoring__platfor_642e86_idx",
                    ),
                    models.Index(
                        fields=["last_checked_at"],
                        name="monitoring__last_ch_7b42a4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
