# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_monitoredaccount_max_posts_per_check_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("facebook", "Facebook")],
                        default="facebook",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
