# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_monitoredaccount_max_posts_per_check_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("facebook", "Facebook")],
                        default="facebook",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text=(
                            "Email address, phone number, or username used for "
                            "platform login."
                        ),
                        max_length=255,
                    ),
                ),
                ("encrypted_password", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_session_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["platform"],
                "indexes": [
                    models.Index(
                        fields=["platform", "is_active"],
                        name="monitoring__platfor_ce7325_idx",
                    ),
                ],
            },
        ),
    ]
