# Generated by Django 5.2.4 on 2026-06-03 02:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_platformcredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("success", "Success"),
                    ("error", "Error"),
                    ("auth_required", "Auth required"),
                    ("skipped", "Skipped"),
                ],
                default="running",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FacebookSessionRefreshRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("token_hint", models.CharField(blank=True, max_length=12)),
                ("operator_url", models.URLField(blank=True, max_length=1000)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("session_path", models.CharField(blank=True, max_length=1000)),
                ("created_session", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
