# Generated by Django 5.2.4 on 2026-06-03 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_alter_checkrun_status_facebooksessionrefreshrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckRunPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("stored", "Stored"), ("skipped", "Skipped")],
                        default="stored",
                        max_length=20,
                    ),
                ),
                ("skip_reason", models.CharField(blank=True, max_length=255)),
                ("external_post_id", models.CharField(max_length=255)),
                ("post_url", models.URLField(blank=True, max_length=1000)),
                ("source_type", models.CharField(blank=True, max_length=100)),
                ("text", models.TextField()),
                ("raw_snapshot", models.TextField(blank=True)),
                ("is_new", models.BooleanField(default=False)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "check_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observed_posts",
                        to="monitoring.checkrun",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_observations",
                        to="monitoring.post",
                    ),
                ),
            ],
            options={
                "ordering": ["check_run", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["check_run", "sequence"],
                        name="monitoring__check_r_c17602_idx",
                    ),
