# Generated by Django 5.2.4 on 2026-06-03 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_alter_checkrun_status_facebooksessionrefreshrequest"),
    ]
