# Generated by Django 5.2.4 on 2026-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_checkrunpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkrun",
            name="article_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="diagnostic_html_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="diagnostic_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="facebook_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="final_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="http_status_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="link_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="page_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="post_link_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="route_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="screenshot_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
