# Generated by Django 5.2.4 on 2026-06-04 01:40

from django.db import migrations, models


TELEGRAM_TEMPLATES = [
    {
        "key": "system_alert",
        "name": "System alert",
        "description": "Generic operational alert sent by the app.",
        "body": "Spy Monitor: {title}\n{lines}",
        "available_placeholders": "title, lines",
    },
    {
        "key": "match_alert",
        "name": "Keyword match alert",
        "description": "Alert sent when a new keyword match is created.",
        "body": (
            "Platform: {platform}\n"
            "Account: {account_name}\n"
            "Keyword: {keyword}\n"
            "Post: {post_url}\n"
            "Preview: {preview}"
        ),
        "available_placeholders": (
            "platform, account_name, keyword, post_url, preview"
        ),
    },
    {
        "key": "bot_help",
        "name": "Bot help",
        "description": "Command list returned by /help.",
        "body": (
            "Commands:\n"
            "/help - show this help.\n"
            "/accounts - list monitored accounts with IDs.\n"
            "/addaccount <facebook|instagram> <url> <name> - add an account.\n"
            "/setaccount <id> <name|url|platform|interval|max_posts|scroll|active> <value> - edit an account.\n"
            "/pauseaccount <id> - pause an account.\n"
            "/resumeaccount <id> - resume an account.\n"
            "/removeaccount <id> - deactivate an account.\n"
            "/keywords - list keywords with IDs.\n"
            "/addkeyword <phrase> - add or reactivate a keyword.\n"
            "/removekeyword <id|phrase> - deactivate a keyword.\n"
            "/pausekeyword <id|phrase> - deactivate a keyword.\n"
            "/resumekeyword <id|phrase> - reactivate a keyword.\n"
            "/check [account_id] [limit] - run checks now. Limit must be 1-20.\n"
            "/matches [limit] - show latest keyword matches.\n"
            "/runs [limit] - show latest check runs.\n"
            "/session - show Facebook session status.\n"
            "/refreshsession - create a Facebook session refresh request."
        ),
        "available_placeholders": "",
    },
    {
        "key": "bot_start",
        "name": "Bot start",
        "description": "Response returned by /start.",
        "body": "Monitoring alerts are enabled for this chat.\n\n{help_text}",
        "available_placeholders": "help_text",
    },
    {
        "key": "bot_error",
        "name": "Bot error",
        "description": "Response returned when a command fails.",
        "body": "Error: {error}",
        "available_placeholders": "error",
    },
    {
        "key": "bot_accounts_empty",
        "name": "Accounts empty",
        "description": "Response when no monitored accounts exist.",
        "body": "No monitored accounts are configured.",
        "available_placeholders": "",
    },
    {
        "key": "bot_accounts",
        "name": "Accounts list",
        "description": "Response for /accounts.",
        "body": "{accounts}",
        "available_placeholders": "accounts, account_count",
    },
    {
        "key": "bot_account_added",
        "name": "Account added",
        "description": "Response after /addaccount succeeds.",
        "body": "Account added: #{account_id} {account_name} ({platform})",
        "available_placeholders": (
            "account_id, account_name, platform, account_url"
        ),
    },
    {
        "key": "bot_account_updated",
        "name": "Account updated",
        "description": "Response after /setaccount succeeds.",
        "body": "Account updated: #{account_id} {account_name} ({field}={value})",
        "available_placeholders": "account_id, account_name, field, value",
    },
    {
        "key": "bot_account_status_changed",
        "name": "Account status changed",
        "description": "Response after pausing or resuming an account.",
        "body": "Account #{account_id} {account_name} is now {status}.",
        "available_placeholders": "account_id, account_name, status",
    },
    {
        "key": "bot_keywords_empty",
        "name": "Keywords empty",
        "description": "Response when no keywords exist.",
        "body": "No keywords are configured.",
        "available_placeholders": "",
    },
    {
        "key": "bot_keywords",
        "name": "Keywords list",
        "description": "Response for /keywords.",
        "body": "{keywords}",
        "available_placeholders": "keywords, keyword_count",
    },
    {
        "key": "bot_keyword_saved",
        "name": "Keyword saved",
        "description": "Response after /addkeyword succeeds.",
        "body": "Keyword {action}: #{keyword_id} {keyword}",
        "available_placeholders": "keyword_id, keyword, action",
    },
    {
        "key": "bot_keyword_status_changed",
        "name": "Keyword status changed",
        "description": "Response after pausing or resuming a keyword.",
        "body": "Keyword #{keyword_id} {keyword} is now {status}.",
        "available_placeholders": "keyword_id, keyword, status",
    },
    {
        "key": "bot_check_no_accounts",
        "name": "Check no accounts",
        "description": "Response when /check has no active accounts to run.",
        "body": "No active monitored accounts were found.",
        "available_placeholders": "",
    },
    {
        "key": "bot_check_finished",
        "name": "Check finished",
        "description": "Response after /check completes.",
        "body": "Check finished: {summary}",
        "available_placeholders": (
            "summary, accounts_checked, posts_found, new_posts_found, "
            "matches_found, errors, auth_required"
        ),
    },
    {
        "key": "bot_matches_empty",
        "name": "Matches empty",
        "description": "Response when no keyword matches exist.",
        "body": "No matches yet.",
        "available_placeholders": "",
    },
    {
        "key": "bot_matches",
        "name": "Matches list",
        "description": "Response for /matches.",
        "body": "{matches}",
        "available_placeholders": "matches, match_count",
    },
    {
        "key": "bot_runs_empty",
        "name": "Runs empty",
        "description": "Response when no check runs exist.",
        "body": "No check runs yet.",
        "available_placeholders": "",
    },
    {
        "key": "bot_runs",
        "name": "Runs list",
        "description": "Response for /runs.",
        "body": "{runs}",
        "available_placeholders": "runs, run_count",
    },
    {
        "key": "bot_session",
        "name": "Facebook session status",
        "description": "Response for /session.",
        "body": (
            "Saved session: {session_status}\n"
            "Credential: {credential_status} {credential_username}\n"
            "Last error: {last_error}\n"
            "Recent requests:\n{recent_requests}"
        ),
        "available_placeholders": (
            "session_status, credential_status, credential_username, "
            "last_error, recent_requests"
        ),
    },
    {
        "key": "bot_session_request_created",
        "name": "Facebook session request created",
        "description": "Response after /refreshsession creates a request.",
        "body": (
            "Facebook session refresh request created: #{request_id}\n"
            "Expires: {expires_at}\n"
            "Operator URL: {operator_url}"
        ),
        "available_placeholders": (
            "request_id, operator_url, expires_at, token_hint"
        ),
    },
]


def seed_telegram_templates(apps, _schema_editor):
    template_model = apps.get_model("monitoring", "TelegramMessageTemplate")
    for template in TELEGRAM_TEMPLATES:
        template_model.objects.update_or_create(
            key=template["key"],
            defaults={
                "name": template["name"],
                "description": template["description"],
                "body": template["body"],
                "available_placeholders": template["available_placeholders"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_checkrun_article_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable template key used by the Telegram bot.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "body",
                    models.TextField(
                        help_text="Use placeholders like {account_name}, {keyword}, or {summary}."
                    ),
                ),
                (
                    "available_placeholders",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated placeholders available for this template.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["key", "is_active"], name="monitoring__key_b14ad2_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="monitoring__updated_495ae5_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_telegram_templates, migrations.RunPython.noop),
    ]
