# Generated by Django 5.2.4 on 2026-06-04 01:40

from django.db import migrations, models


TELEGRAM_TEMPLATES = [
    {
        "key": "system_alert",
        "name": "System alert",
        "description": "Generic operational alert sent by the app.",
        "body": "Spy Monitor: {title}\n{lines}",
        "available_placeholders": "title, lines",
    },
    {
        "key": "match_alert",
        "name": "Keyword match alert",
        "description": "Alert sent when a new keyword match is created.",
        "body": (
            "Platform: {platform}\n"
            "Account: {account_name}\n"
            "Keyword: {keyword}\n"
            "Post: {post_url}\n"
            "Preview: {preview}"
        ),
        "available_placeholders": (
            "platform, account_name, keyword, post_url, preview"
        ),
    },
    {
        "key": "bot_help",
        "name": "Bot help",
        "description": "Command list returned by /help.",
        "body": (
            "Commands:\n"
            "/help - show this help.\n"
            "/accounts - list monitored accounts with IDs.\n"
            "/addaccount <facebook|instagram> <url> <name> - add an account.\n"
            "/setaccount <id> <name|url|platform|interval|max_posts|scroll|active> <value> - edit an account.\n"
            "/pauseaccount <id> - pause an account.\n"
            "/resumeaccount <id> - resume an account.\n"
            "/removeaccount <id> - deactivate an account.\n"
            "/keywords - list keywords with IDs.\n"
            "/addkeyword <phrase> - add or reactivate a keyword.\n"
            "/removekeyword <id|phrase> - deactivate a keyword.\n"
            "/pausekeyword <id|phrase> - deactivate a keyword.\n"
            "/resumekeyword <id|phrase> - reactivate a keyword.\n"
            "/check [account_id] [limit] - run checks now. Limit must be 1-20.\n"
            "/matches [limit] - show latest keyword matches.\n"
            "/runs [limit] - show latest check runs.\n"
            "/session - show Facebook session status.\n"
            "/refreshsession - create a Facebook session refresh request."
        ),
        "available_placeholders": "",
    },
    {
        "key": "bot_start",
        "name": "Bot start",
        "description": "Response returned by /start.",
        "body": "Monitoring alerts are enabled for this chat.\n\n{help_text}",
        "available_placeholders": "help_text",
    },
    {
        "key": "bot_error",
        "name": "Bot error",
        "description": "Response returned when a command fails.",
        "body": "Error: {error}",
        "available_placeholders": "error",
    },
    {
        "key": "bot_accounts_empty",
        "name": "Accounts empty",
        "description": "Response when no monitored accounts exist.",
        "body": "No monitored accounts are configured.",
        "available_placeholders": "",
    },
    {
        "key": "bot_accounts",
        "name": "Accounts list",
        "description": "Response for /accounts.",
        "body": "{accounts}",
        "available_placeholders": "accounts, account_count",
    },
    {
        "key": "bot_account_added",
        "name": "Account added",
        "description": "Response after /addaccount succeeds.",
        "body": "Account added: #{account_id} {account_name} ({platform})",
        "available_placeholders": (
            "account_id, account_name, platform, account_url"
        ),
    },
    {
        "key": "bot_account_updated",
        "name": "Account updated",
        "description": "Response after /setaccount succeeds.",
        "body": "Account updated: #{account_id} {account_name} ({field}={value})",
