# Generated by Django 5.2.4 on 2026-06-04 01:40

from django.db import migrations, models


TELEGRAM_TEMPLATES = [
    {
        "key": "system_alert",
        "name": "System alert",
        "description": "Generic operational alert sent by the app.",
        "body": "Spy Monitor: {title}\n{lines}",
        "available_placeholders": "title, lines",
