# Generated by Django 5.2.4 on 2026-06-04 01:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


BOT_HELP = """Commands:
/help - show this help.
/keywords - list keywords with IDs.
/addkeyword <phrase> - add or reactivate a keyword.
/pausekeyword <id|phrase> - deactivate a keyword.
/resumekeyword <id|phrase> - reactivate a keyword.
/check [account_id] [limit] - run checks now. Limit must be 1-20.
/matches [limit] - show latest keyword matches.
/runs [limit] - show latest check runs.
/session - show Facebook session status.
/refreshsession - create a Facebook session refresh request."""

REMOVED_TEMPLATE_KEYS = [
    "bot_accounts_empty",
    "bot_accounts",
    "bot_account_added",
    "bot_account_updated",
    "bot_account_status_changed",
]


def update_telegram_help(apps, _schema_editor):
    template_model = apps.get_model("monitoring", "TelegramMessageTemplate")
    template_model.objects.filter(key="bot_help").update(body=BOT_HELP)
    template_model.objects.filter(key__in=REMOVED_TEMPLATE_KEYS).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_telegrammessagetemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualCheckJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("accounts_checked", models.PositiveIntegerField(default=0)),
                ("posts_found", models.PositiveIntegerField(default=0)),
                ("new_posts_found", models.PositiveIntegerField(default=0)),
                ("matches_found", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("auth_required", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_check_jobs",
                        to="monitoring.monitoredaccount",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_check_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
