# Generated by Django 5.2.4 on 2026-07-07 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("query", models.TextField()),
                (
                    "depth",
                    models.CharField(
                        choices=[
                            ("quick", "Quick"),
                            ("standard", "Standard"),
                            ("deep", "Deep"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("include_social", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("planning", "Planning"),
                            ("collecting", "Collecting"),
                            ("social_collecting", "Social collecting"),
                            ("critiquing", "Critiquing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("external_job_id", models.CharField(blank=True, max_length=255)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("report_markdown", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="research.researchjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("social", "Social"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("excerpt", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="research.researchjob",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "title", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="researchjob",
            index=models.Index(
                fields=["status", "created_at"], name="research_re_status_4adb58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchjob",
            index=models.Index(
                fields=["requested_by", "created_at"],
                name="research_re_request_2d8dbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchjob",
            index=models.Index(
                fields=["external_job_id"], name="research_re_externa_ef9da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchevent",
            index=models.Index(
                fields=["job", "created_at"], name="research_re_job_id_67f9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchevent",
            index=models.Index(
                fields=["level", "created_at"], name="research_re_level_0a3c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsource",
            index=models.Index(
                fields=["job", "source_type"], name="research_re_job_id_6c63b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchsource",
            index=models.Index(
                fields=["created_at"], name="research_re_created_545994_idx"
            ),
        ),
    ]
