# Generated by Django 5.2.4 on 2026-09-24 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research",
            "0002_facebookcomment_facebookpost_facebookcommentrevision_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookDiscoverySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("group", "Public group"),
                            ("search", "Search phrase"),
                        ],
                        max_length=12,
                    ),
                ),
                ("target", models.CharField(max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "target"), name="fb_discovery_source_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FacebookDiscoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("kind", models.CharField(max_length=12)),
                ("target", models.CharField(max_length=500)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("coverage", models.CharField(blank=True, max_length=80)),
                ("error", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("cycle_attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
