# Generated by Django 5.2.4 on 2026-09-24 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research",
            "0002_facebookcomment_facebookpost_facebookcommentrevision_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookDiscoverySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
