# Generated by Django 5.2.4 on 2026-09-24 05:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_facebookdiscoverysource_facebookdiscoveryrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="backfill_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="refresh_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchjob",
            name="monitor_lane",
            field=models.CharField(blank=True, db_default="", max_length=12),
        ),
        migrations.CreateModel(
            name="FacebookMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("pause_reason", models.TextField(blank=True)),
                (
                    "discovery_hours",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "refresh_hours",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "backfill_hours",
                    models.PositiveIntegerField(
                        default=12,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "refresh_batch",
                    models.PositiveIntegerField(
                        default=12,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
