# Generated by Django 5.2.4 on 2026-09-24 05:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_facebookdiscoverysource_facebookdiscoveryrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="backfill_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="refresh_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchjob",
            name="monitor_lane",
            field=models.CharField(blank=True, db_default="", max_length=12),
        ),
        migrations.CreateModel(
            name="FacebookMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
