# Generated by Django 5.2.4 on 2026-09-24 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_facebookpost_backfill_queued_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
